### ISSUE TITLE
I'm getting any response

### ISSUE THREAD

**Issue by orafaelreis** [danylokostyshyn/popcorntime-ios#12]
Please, the second and third tabs doesn't result any data. I'm inspect the request and the API at cloudflare doesn't output data. What is wrong? Thanks in advance!

**Comment by danylokos** [comment]
popcorntime.io servers are down, sadly, but, i don't think it will ever work again :(

**Comment by solderzzc** [comment]
I modified the original popcorn api server to provide EZTV/YTS.io wrapper.
Code is opened on https://github.com/solderzzc/popcorn-show-api-server
Also I have a private host for testing.
