### ISSUE TITLE
Errors while archiving?

### ISSUE THREAD

**Issue by hayzamjs** [danylokostyshyn/popcorntime-ios#16]
I wanted to build for the new APIs! But I got these four errors, help me ?
http://imgur.com/ufwneH5

These are the errors, if you could help me it would be awesome!

**Comment by danylokos** [comment]
HI, first two errors aren't critical, (Xcode tries to upload symbols to Fabric), archiving process should still succeed, and i just added a check to pass this. And the rest - i have no idea what they are, i've just tried to make a fresh clone and i've been able to archive the project without  the errors. I'm using Xcode 7.1.1 (7B1005)

**Comment by hayzamjs** [comment]
Oh I was using 7.0.1 to archive, I'll try updating and then try to archive again! Thanks for the reply though :)

**Comment by hayzamjs** [comment]
I updated to 7.1.1, and now I'm using this fork https://github.com/BuddyBuildTeam/popcorntime-ios/tree/patch-1 since it doesn't seem to have fabric, anyway, now I get http://pastebin.com/0REzk1ki 
the 2 errors, what could this possibly be?

EDIT : It works flawlessly inside of the simulator, but I cannot archive or try to run on my device then it shows the errors above and I also tried with the original git repo, the fabric issue disappeared after updating to 7.1.1 but the unrecognized option: --toolchain and Couldn't copy and strip bitcode /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/libswiftFoundation.dylib to /Users/Hayzam/Library/Developer/Xcode/DerivedData/PopcornTime-btgknvzgfhqybibwokkwffxtdtov/Build/Products/Debug-iphoneos/PopcornTime.app/Frameworks/libswiftFoundation.dylib: bitcode_strip failed with exit code 64
Persists! :sob:
