### ISSUE TITLE
TV shows working

### ISSUE THREAD

**Issue by Rand-o** [danylokostyshyn/popcorntime-ios#17]
Tv shows api replaced with 
"https://www.popcorntime.ws/api/eztv/"
there is a working Movies api 
"yts.ag/api/vs/list_movies.json"
but it doesn't work in the app... suspect the parsing of the movie information is different then the previous api

**Comment by carlyd95** [comment]
@Rand-o I just came here to see if the fix at: https://www.reddit.com/r/PopCornTime/comments/3sbsz6/download_working_installers_or_fix_your_current/ worked with this. thanks! you think someone could update the app to work with the new movies api?

**Comment by popcorntimeios** [comment]
@carlyd95 these forks have working movie section
https://github.com/sanghviharshit/popcorntime-ios
https://github.com/popcorntimeios/popcorntimeios

**Comment by carlyd95** [comment]
Appreciate it

Carly-D
