### ISSUE TITLE
Butter Project

### ISSUE THREAD

**Issue by xaiki** [danylokostyshyn/popcorntime-ios#18]
Hey there, i've been looking at what you've been doing and i think we may be able to use your work and exeperience in https://github.com/butterproject/ would you be interested ?

**Comment by danylokos** [comment]
Hi, thanks but i'm not interested in the project for now, but yes, you can use the source code. But i think that the main part - streamer should be rewritten, because current algorithm for piece picking is not very effective.

**Comment by xaiki** [comment]
thanks for your time (and code ;))
