### ISSUE TITLE
cannot build with free account

### ISSUE THREAD

**Issue by sasagr** [danylokostyshyn/popcorntime-ios#20]
I cannot build it with a free dev account because it includes In App Purchase, feature only present with paid dev account.
Is there a way to disable it and make build possible with free dev account?

**Comment by haawa799** [comment]
@sasagr 
This should do the trick:

<img width="1141" alt="screen shot 2016-05-30 at 4 01 01 pm" src="https://cloud.githubusercontent.com/assets/1273235/15650276/0910ec16-2680-11e6-903f-2c205fc9f757.png">

**Comment by saitohirga** [comment]
I would like to add, you have to do it fast, it goes away really fast, so if you can't find it you have to redownload it.

**Comment by sasagr** [comment]
yes. as matter of fact I could not see it and looking around I m understanding that this is only visible to paid dev accounts.
In any case I managed to build it. I just did not click on fix for the signature and it worked. Strangely but it worked.
