### ISSUE TITLE
Can't disable in-app purchase 

### ISSUE THREAD

**Issue by Ge3kSn0w** [danylokostyshyn/popcorntime-ios#22]
Hey love what your doing but every time I try to disable in-app purchase it keeps turning back on. Any ideas. I am running the Xcode 8 beta.

**Comment by saitohirga** [comment]
You gotta do this really fast, redownload code and coco pods, then turn it off.

**Comment by Ge3kSn0w** [comment]
I tried that and it turned its self back on.

[Untitled.zip](https://github.com/danylokostyshyn/popcorntime-ios/files/337583/Untitled.zip)

**Comment by danylokos** [comment]
Disabled in-app purchase in the settings. But they were never implemented any way, so not sure why it's an issue.
