### ISSUE TITLE
update to swift 3

### ISSUE THREAD

**Issue by senghuot** [danylokostyshyn/popcorntime-ios#24]
looks like CocoaPods just got an update. Also, the project now requires Swift3 to build. I have a hard time building this project. Do you any new instructions or planning to update this project?

**Comment by senghuot** [comment]
So i managed to update to SWIFT 3.0 would you like me to do a pull request?

**Comment by haawa799** [comment]
@senghuot Sure, go for it, do a PR.

**Comment by danylokos** [comment]
Hi, also just updated it, mostly through auto-convert tool, already pushed. I'm not sure how stable the app is right now, and how reliable are the servers. I think that there are other forks/versions now, which have more features, and are being maintained very well.

**Comment by senghuot** [comment]
@haawa799 looks like Dany beat me to it haha.
@danylokostyshyn  kool beans thanks for the update. 

I'll see if i can contribute and close some of the issues. this is why i love the open source community :)
