### ISSUE TITLE
Add to favorite doesn't work

### ISSUE THREAD

**Issue by senghuot** [danylokostyshyn/popcorntime-ios#27]
The problem boils down to this highlighted code. I'm in-experienced with Swift and IOS Dev in general. Trying to work out a solution but looks like we trouble decode the ImageType. If anyone knows the solution please do a pull request.

![screen shot 2017-01-03 at 10 59 12 pm](https://cloud.githubusercontent.com/assets/6964567/21633949/45fa6736-d208-11e6-8a5b-82b99336df7a.png)

**Comment by danylokos** [comment]
Fixed 555aff8d10e38870ef58e75c1af35e5494547c98
