### ISSUE TITLE
I got strange compile error

### ISSUE THREAD

**Issue by solderzzc** [danylokostyshyn/popcorntime-ios#7]
I got compile error 'Verify final result code for completed build operation  Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons. Some of these (up to 12) may be listed below.' 

Mac OSX 10.10.4
Xcode 6.4
COCOAPODS: 0.38.2

![screen shot 2015-08-06 at 12 57 46 pm](https://cloud.githubusercontent.com/assets/3085564/9121969/d0854944-3c3a-11e5-82eb-5990392e71fe.png)

**Comment by danylokos** [comment]
Have the same error when using CocoaPods 0.38.2, i don't know why, i'm currently investigating this. Try to rollback to 0.37.2, i've just tried with 0.37.2 and everything worked ok.

**Comment by dogaoz** [comment]
same error here

**Comment by danylokos** [comment]
It's a problem with CocoaPods 0.38.x, try using 0.37.2 or latest 0.39.0.beta.4.

**Comment by SureshReddis19** [comment]
Try compiling after removing the Input Files which are created from Shell Script **under Target -> Build Phases -> [CP] Copy Pods Resources**
